// potatoFacts.js
module.exports = [
    "The word 'potato' comes from a blend of the Taino word 'batata' (sweet potato) and the Quechua word 'papa' (the Andean potato).",
    "Potatoes were first domesticated by the Inca people in Peru around 8,000 to 5,000 BC.",
    "China is currently the world’s largest producer of potatoes, followed by India and Russia.",
    "Potatoes are the fourth most important food crop in the world after wheat, rice, and maize.",
    "The Spanish brought potatoes to Europe in the second half of the 16th century.",
    "Sir Walter Raleigh is credited with helping to popularize the potato in Ireland in the late 16th century.",
    "Potatoes were the first vegetable to be grown in space—on the Space Shuttle Columbia in 1995.",
    "The 'Great Famine' in Ireland (1845–1849) was caused by a potato disease known as late blight.",
    "Potatoes are about 80% water and 20% solids.",
    "Marie Antoinette once wore potato blossoms in her hair to make a fashion statement.",
    "Potatoes can absorb and reflect Wi-Fi signals, which is why they’ve been used in some Wi-Fi testing.",
    "A raw potato can help clean a foggy mirror if rubbed across the surface.",
    "The average American eats roughly 140 pounds of potatoes per year.",
    "Potatoes contain significant amounts of vitamin C, potassium, vitamin B6, and manganese.",
    "The world's largest potato recorded weighed around 11 pounds (about 5 kg).",
    "There are over 4,000 varieties of native potatoes found in the Andes alone.",
    "Potatoes are grown in more than 100 countries worldwide.",
    "Idaho is famous for its potatoes in the United States, although many states grow them.",
    "The first published recipe for french fries appears in an English cookbook from 1856.",
    "Potatoes were once believed to be poisonous by some Europeans because they are a member of the nightshade family.",
    "The 'eyes' of a potato are actually buds from which new potato plants can sprout.",
    "In 1995, NASA and the University of Wisconsin created the technology to grow potatoes in space.",
    "Potatoes can be used to brew a type of alcoholic beverage known as 'potato beer' or 'potato vodka'.",
    "The International Potato Center in Peru maintains a gene bank of over 7,000 potato accessions.",
    "Potatoes can be stored for several months if kept in a cool, dark, and dry place.",
    "The skins of potatoes contain fiber, vitamin C, and other nutrients—so eating them with the skin can be beneficial.",
    "The heaviest potato consumption per capita is in Belarus, with around 180–200 pounds per person per year.",
    "Potatoes were initially used in Europe to feed animals before they became a staple human food.",
    "A 'New Potato' is one harvested while still small and immature, prized for its tender skin and sweet flavor.",
    "Potatoes are naturally gluten-free, making them a popular carbohydrate source for those with gluten intolerance.",
    "The potato plant produces white, pink, red, blue, or purple flowers on top of green stems.",
    "When exposed to light, potato skins can turn green and develop a toxin called solanine, which is harmful in large amounts.",
    "The first successful commercial potato chip brand in the U.S. was Lay’s, introduced in 1932.",
    "The term 'couch potato' was coined in the late 1970s to describe someone who sits on the couch watching TV.",
    "The 'potato clock' science experiment demonstrates how potatoes can generate a small electric current.",
    "In Andean culture, potatoes have historically been used to predict weather by observing sprouting patterns.",
    "The name 'spud' for potato is believed to have originated from a 19th-century anti-potato group called the Society for the Prevention of an Unwholesome Diet (S.P.U.D.), though this is debated.",
    "Potatoes are the first food to have been planted on all seven continents (yes, even Antarctica in research stations).",
    "In Germany, there's a potato dumpling dish called 'Kartoffelklöße' or 'Kartoffelknödel,' a classic comfort food.",
    "The Andean natives traditionally freeze-dry potatoes to make 'chuño,' which can be stored for years.",
    "The potato was declared the official state vegetable of Idaho in 2002.",
    "In 1996, the European Union recognized the 'Protected Geographical Indication' of certain regional potato varieties.",
    "'Pommes frites' (French fries) are said to have originated in Belgium, though France also claims the origin.",
    "Some people use slices of raw potato to soothe minor skin irritations or burns (though this is anecdotal).",
    "The Incas measured time by how long it took to cook a potato—a practical timekeeping method.",
    "Potatoes are related to tomatoes, peppers, and eggplants, all members of the nightshade family.",
    "The largest producer of potatoes in the U.S. is Idaho, followed by Washington and Wisconsin.",
    "The Spanish term for potato is 'patata,' while in many Latin American countries it’s 'papa.'",
    "'Gnocchi' is an Italian dumpling often made from potatoes, flour, and eggs.",
    "Potatoes can be prepared in countless ways: baked, mashed, fried, roasted, boiled, steamed, or grilled.",
    "The 'All Blue' potato is a variety known for its deep blue-purple skin and flesh.",
    "Potato starch is used in the textile industry and in paper manufacturing.",
    "The world's largest potato-producing continent is Asia, due to China and India’s huge outputs.",
    "French fries were introduced to the U.S. by Thomas Jefferson, who served them at the White House in 1802.",
    "Potatoes can be stored as 'seed potatoes' to grow new plants the following season.",
    "A medium potato has about 110 calories, if eaten plain with the skin on.",
    "The phrase 'hot potato' refers to a controversial or awkward issue that’s difficult to handle.",
    "'Latkes' are potato pancakes traditionally eaten during the Jewish festival of Hanukkah.",
    "The Russians use potatoes in many traditional dishes, including 'draniki' (potato pancakes).",
    "Potatoes were partially responsible for population booms in Europe in the 18th and 19th centuries due to their caloric density.",
    "The Japanese dish 'korokke' is a deep-fried patty made with mashed potato and minced meat or vegetables.",
    "In Peru, the International Potato Center researches potato biodiversity to improve food security.",
    "'Boxty' is a traditional Irish potato pancake, often served with butter or sour cream.",
    "The color of potato flowers can hint at the color of the potato skin beneath the soil (though not always precisely).",
    "Potatoes are sometimes used in gardening to help break up heavy soils when planted in rotation.",
    "The 'Potato Paradox' is a mathematical puzzle about changing water content in potatoes, illustrating percentages.",
    "Potato skins contain beneficial phytochemicals, which may help lower blood pressure.",
    "'Patatas bravas' is a famous Spanish tapa dish of fried potatoes served with a spicy sauce.",
    "The Incas developed over 2,000 different varieties of potatoes, adapted to various microclimates in the Andes.",
    "Raw potato juice is sometimes touted in folk remedies for digestive issues, though scientific evidence is limited.",
    "In Ireland, 'champ' is mashed potatoes mixed with scallions, butter, and milk.",
    "The 'Potato Museum' in Washington D.C. (now mostly virtual) highlights the crop’s history and cultural impact.",
    "The phrase 'meat and potatoes' means the basic or most essential part of something.",
    "Potatoes can be grown in containers, bags, or small gardens, making them accessible for urban farming.",
    "The 'eyes' of a potato will sprout if stored in warm, bright conditions, so keep them cool and dark.",
    "The Yukon Gold potato was developed in Canada in the 1960s and is prized for its buttery flavor.",
    "During the Klondike Gold Rush, potatoes were valued for their vitamin C content to prevent scurvy.",
    "Some varieties of potatoes have naturally purple or blue flesh, rich in antioxidants.",
    "The 'Maris Piper' potato is the most widely grown potato variety in the UK, great for chips and roasting.",
    "Potatoes are a staple food in many African countries, including Malawi and Rwanda.",
    "The largest potato-growing region in Canada is Prince Edward Island, famous for red soil and spuds.",
    "'Hasselback potatoes' are a Swedish dish, thinly sliced not all the way through, then baked with butter or oil.",
    "'Tater tots' were invented by the founders of Ore-Ida to use leftover potato scraps.",
    "The scientific name for the potato plant is Solanum tuberosum.",
    "The biggest threat to potato crops worldwide is late blight, caused by the fungus-like organism Phytophthora infestans.",
    "Potatoes can be used to make biodegradable cutlery and packaging materials.",
    "The phrase 'couch potato' originated in the U.S. in the late 1970s to describe a TV-addicted person.",
    "Peru holds the world record for the largest potato stew, 'carapulcra,' prepared with dried potatoes and pork.",
    "In some cultures, potatoes were once used as a remedy for rheumatism or warts (though not scientifically proven).",
    "The USDA classifies potatoes as a vegetable, though nutritionally they’re often grouped with starches.",
    "Potatoes are naturally cholesterol-free, fat-free, and sodium-free (until toppings are added).",
    "The earliest archaeological evidence of potato consumption is from the coastal site of Ancón, Peru.",
    "Potatoes grow best in well-drained, loose soil with a pH of around 5.0–6.0.",
    "'Aligot' is a French dish made from mashed potatoes blended with cheese (traditionally Tomme), butter, and garlic.",
    "In the U.S., National Potato Day is celebrated on August 19th.",
    "Potato plants produce small, poisonous fruits resembling green tomatoes, which are not edible.",
    "The term 'French fry' in the U.S. likely comes from the method of 'Frenching' (cutting into thin strips).",
    "In parts of India, 'aloo' means potato, leading to dishes like 'aloo gobi' (potato and cauliflower).",
    "The potato is so integral to Andean culture that the Quechua language has over a thousand words for different potato varieties.",
    "Potatoes were once considered an aphrodisiac in 16th-century Europe, though this claim lacked scientific basis."
  ];
  